#!/usr/bin/env csh
#
# joosc: compiles JOOS source programs into class files using the A- JOOS compiler.
#
# usage:  joosc f1.java f2.java ... fn.joos
#  
# note:  you should name each source file for ordinary classes with
#        .java extensions and all external classes with .joos extensions

if ( { '/home/2014/tyang15/PeepholeContest/joos' $* } )  then
  foreach f ( $* )
    if ( $f != "-O" && $f:e != "joos" ) then
      java -jar /home/2014/tyang15/PeepholeContest/jasmin.jar $f:r.j 
    endif
  end
endif
