#!/usr/bin/env bash

# compile JOOS programs using the A- compiler.

# assumes JOOSDIR is set properly
# assumes a binary called `joos' is on PATH

/home/2014/tyang15/PeepholeContest/JOOSA-src/joos $* /home/2014/tyang15/PeepholeContest/JOOSexterns/*.joos
