# assumes sablecc script is on your PATH

# to compile the code
joosc: clean
	/home/2014/tyang15/PeepholeContest/joosc *.java

java: clean
	javac *.java

check:	
	./check.py

clean:	
	rm -rf *.class *.j
