all: clean
	/home/2014/tyang15/PeepholeContest/joos BacktrackSolver.java SudokuSolver.java Benchmark.java

java:
	/home/2014/tyang15/PeepholeContest/joos BacktrackSolver.java SudokuSolver.java Benchmark.java

clean:	
	rm -rf *.class *.j *~

run:
	java Benchmark < in1
